Анофриков Александр
VK-BMSTU-QA/units-spring-2023 pull request #10
Opened 2023-03-10 17:24 UTC by Andeo1812

2023-03-10 17:56 UTC, Ivan-Bir commented
Аппрув

2023-03-11 12:58 UTC, lonkidely commented
Аппрув

2023-03-11 12:59 UTC, lonkidely approved these changes
Аппрув

2023-03-12 09:23 UTC, Mike5535 commented
Аппрув

2023-03-19 18:52 UTC, Andeo1812 commented
UPD

2023-03-19 19:02 UTC, alexey-ershkov requested changes
Приветы, накинул комментов

2023-03-19 19:02 UTC, alexey-ershkov commented on src/utils/__tests__/productComparator.test.ts
> +    it('return 1 if sortBy === по возрастанию цены and 1 product > 2 product', () => {
кажется it-ы можно объединить по типу сортировки, так будет лучше

плюс можно создать всего два объекта и с помощью spread оператора менять по месту цены, так будет нагляднее, чем просто все брать из подготовленных данных

2023-03-19 19:02 UTC, alexey-ershkov commented on src/utils/__tests__/updateCategories.test.ts
> +});
тоже потерял перенос строки в конце

2023-03-19 19:02 UTC, alexey-ershkov commented on src/utils/__tests__/updateCategories.test.ts
> +  let categories : Category [] = [
const

2023-03-19 19:02 UTC, alexey-ershkov commented on src/utils/__tests__/updateCategories.test.ts
> +  it('return categories with new changedCategory', () => {
тут можно тоже по месту написать, будет нагляднее и читаемее

2023-03-20 09:51 UTC, Andeo1812 commented on src/components/ProductCard/ProductCard.test.tsx
> +    let product: Product = {
+

2023-03-20 09:51 UTC, Andeo1812 commented on src/components/SortButton/SortButton.test.tsx
> +});
+

2023-03-20 09:52 UTC, Andeo1812 commented on src/utils/__tests__/applyCategories.test.ts
> +});
+

2023-03-20 09:52 UTC, Andeo1812 commented on src/utils/__tests__/applyCategories.test.ts
> +  let categoryTestDataBefore : Category[] = [
+

2023-03-20 09:52 UTC, Andeo1812 commented on src/utils/__tests__/applyCategories.test.ts
> +  let productsTestDataBefore : Product[] = [
+

2023-03-20 09:54 UTC, Andeo1812 commented on src/utils/__tests__/getNextSortBy.text.ts
> +});
+

2023-03-20 09:55 UTC, Andeo1812 commented on src/utils/__tests__/updateCategories.test.ts
> +});
+

2023-03-20 09:55 UTC, Andeo1812 commented on src/utils/__tests__/updateCategories.test.ts
> +  let categories : Category [] = [
+

2023-03-20 10:02 UTC, Andeo1812 commented on src/utils/__tests__/applyCategories.test.ts
> +describe("test applyCategories function - OK", () => {
+

2023-03-21 19:50 UTC, Andeo1812 commented on src/components/ProductCard/ProductCard.test.tsx
> +    return {
+

2023-03-21 20:26 UTC, Andeo1812 commented on src/utils/__tests__/productComparator.test.ts
> +    it('return 1 if sortBy === по возрастанию цены and 1 product > 2 product', () => {
+

2023-03-21 20:26 UTC, Andeo1812 commented on src/components/ProductCard/ProductCard.test.tsx
> +        expect(rendered.asFragment()).toMatchSnapshot();
+

2023-03-21 20:28 UTC, Andeo1812 commented on src/pages/MainPage/MainPage.test.tsx
> +    const rendered = render(
+

2023-03-23 19:37 UTC, alexey-ershkov requested changes
Привет, накинул пару комментов, на исправления два дня до субботы включительно

2023-03-23 19:37 UTC, alexey-ershkov commented on src/components/ProductCard/ProductCard.test.tsx
> +import {render} from '@testing-library/react';
Пройдись линтером с фиксом, чет все форматирование слетело

2023-03-23 19:37 UTC, alexey-ershkov commented on src/pages/MainPage/MainPage.test.tsx
> +        if (!categories.length) return products;
Почему не упростить мок и не возвращать всегда одно и то же значение?

2023-03-25 13:58 UTC, Andeo1812 commented on src/pages/MainPage/MainPage.test.tsx
> +        if (!categories.length) return products;
+

2023-03-25 13:58 UTC, Andeo1812 commented on src/components/ProductCard/ProductCard.test.tsx
> +import {render} from '@testing-library/react';
+

2023-03-26 09:03 UTC, alexey-ershkov approved these changes
Сдано, 5 баллов

2023-03-28 06:32 UTC, closed without merging